/**
 * Data Health Checker
 * Usage: node scripts/check_duplicates.js
 */
const fs = require('fs');
const path = require('path');

// Adjust this path if your script is in root vs scripts folder
// Current setting: assumes script is in 'scripts/' and data is in '../js/'
const DATA_FILE_PATH = path.join(__dirname, '../js/data-embedded.js');

console.log("🔍 Scanning data file...");

let itemsData;
try {
    const fileContent = fs.readFileSync(DATA_FILE_PATH, 'utf8');
    const dataMatch = fileContent.match(/const ITEMS_DATA = (\[[\s\S]*?\]);/);
    if (!dataMatch) throw new Error("Could not parse ITEMS_DATA array.");
    itemsData = eval('(' + dataMatch[1] + ')');
} catch (e) {
    console.error("❌ Error reading data:", e.message);
    process.exit(1);
}

// 1. Check for Duplicate IDs
const idMap = new Map();
const duplicates = [];

itemsData.forEach((item, index) => {
    if (idMap.has(item.id)) {
        duplicates.push({ id: item.id, name: item.name, index: index });
    } else {
        idMap.set(item.id, item.name);
    }
});

if (duplicates.length > 0) {
    console.log('\n🔴 DUPLICATE ITEMS (Delete one of these):');
    duplicates.forEach(d => console.log(`   - ID ${d.id}: "${d.name}" (Found again at index ${d.index})`));
} else {
    console.log('\n✅ No duplicate IDs found.');
}

// 2. Check for Slug/URL Collisions
function createSlug(text) {
    return text.toString().toLowerCase()
        .replace(/[()]/g, '')
        .replace(/\//g, '-')
        .replace(/[^\w\s-]/g, '')
        .replace(/\s+/g, '-')
        .replace(/-+/g, '-')
        .trim();
}

const slugMap = new Map();
const slugCollisions = [];

itemsData.forEach(item => {
    const slug = createSlug(item.name);
    if (slugMap.has(slug)) {
        slugCollisions.push({ slug: slug, original: slugMap.get(slug), conflict: item.name });
    } else {
        slugMap.set(slug, item.name);
    }
});

if (slugCollisions.length > 0) {
    console.log('\n🔴 URL CONFLICTS (Rename one of these to be unique):');
    slugCollisions.forEach(c => {
        console.log(`   - Slug "${c.slug}" is generated by BOTH:`);
        console.log(`     1. "${c.original}"`);
        console.log(`     2. "${c.conflict}"`);
    });
} else {
    console.log('\n✅ No URL conflicts found.');
}